/* Generated by buffc.lua - do not edit. */
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include "buff_runtime.h"
#include <stdio.h>

typedef struct Player {
    int hp;
    float speed;
} Player;

void damage_player(Player* p, int amount);
int main(void);

void damage_player(Player* p, int amount) {
    (p->hp = (p->hp - amount));
}

int main(void) {
    Player* hero = (Player*)arena_alloc(&game_arena, sizeof(Player));
    (hero->hp = 100);
    damage_player(hero, 25);
    printf("HP: %d", hero->hp); printf("\n");
    return 0;
}

